#X-Generator: crowdin.com
# Content-related messages

content.content_missing=The node''s content is missing\: \n   node\: {0} \n   reader\: {1}  \n   Please contact your system administrator.
content.runtime_exec.property_moved=The property ''errorCodes'' has moved down onto the RuntimeExec class

index.recovery.out_of_date=The indexes are not synchronized with the database.
index.tracking.starting=\u0418\u043d\u0434\u0435\u043a\u0441\u043d\u043e\u0442\u043e \u0432\u0440\u0430\u045c\u0430\u045a\u0435 \u0437\u0430\u043f\u043e\u0447\u043d\u0430.
index.tracking.complete=\u0418\u043d\u0434\u0435\u043a\u0441\u043d\u043e\u0442\u043e \u0432\u0440\u0430\u045c\u0430\u045a\u0435 \u0437\u0430\u0432\u0448\u0438.
index.tracking.progress=\tProcessing transactions around {0}.
index.recovery.starting=Index recovery started\: {0} transactions.
index.recovery.complete=\u0418\u043d\u0434\u0435\u043a\u0441\u043d\u043e\u0442\u043e \u0432\u0440\u0430\u045c\u0430\u045a\u0435 \u0437\u0430\u043f\u043e\u0447\u043d\u0430.
index.recovery.progress={0} % \u0437\u0430\u0432\u0440\u0448\u0435\u043d\u043e.
index.recovery.terminated=Index recovery terminated.

node.archive.msg.busy=A bulk purge or restore operation is currently in progress

content.http_reader.err.no_connection=\u041d\u0435 \u043c\u043e\u0436\u0435 \u0434\u0430 \u0441\u0435 \u043f\u043e\u0432\u0440\u0437\u0435 \u0441\u043e Alfresco \u043e\u0434\u0434\u0430\u043b\u0435\u0447\u0435\u043d \u0441\u0435\u0440\u0432\u0435\u0440 \u043f\u0440\u0435\u043a\u0443 HTTP\:{0}
content.http_reader.err.no_authentication=The HTTP reader was unable to authenticate on the remote server\: {0}  \n
content.http_reader.err.check_cluster=Please ensure that ''replicateUpdates'' and ''replicateUpdatesViaCopy'' is enabled for the cache ''org.alfresco.cache.ticketsCache''.  Check that the general cluster configuration is correct and working.
content.http_reader.err.unrecognized=An unrecognized error occurred when attempting to download content from remote server\:\n   Server\: {0} \n   Content\: {1} \n   HTTP Response\: {2}

metadata.extraction.err.type_conversion=Metadata extraction failed because an extracted value failed to convert to the required type\: \n   Extractor\: {0} \n   Target Property QName\: {1} \n   Required Type\: {2} \n   Extracted Value\: {3}

transform.err.format_or_password=Failed to convert content, possibly due to an incorrectly formatted or password protected file.

content.routing.err.invalid_default_store=The ''defaultStoreName'', ''{0}'' does not refer to a store in ''storesByName'' ({1}).
