#X-Generator: crowdin.com
# authentication error messages
authentication.err.validation.authenticator.notfound=Nezda\u0159ilo se ov\u011b\u0159en\u00ed. Autentik\u00e1tor {0} nebyl nalezen
authentication.err.validation.authenticator.notactive=Autentik\u00e1tor nen\u00ed aktivn\u00ed

authentication.err.authentication=Autentizace se nezda\u0159ila. U\u017eivatelsk\u00e9 jm\u00e9no {0} nebo heslo jsou chybn\u00e9. D\u016fvod\: {1}
authentication.err.connection=Nepoda\u0159ilo se p\u0159ipojit k {0}. D\u016fvod\: {1}
authentication.err.communication=Nelze komunikovat s {0}. D\u016fvod\: {1}

# LDAP error messages
authentication.err.connection.ldap.authenticator.unknownhost=Nepoda\u0159ilo se p\u0159ipojit, ldap hostitel {0} je nezn\u00e1m\u00fd
authentication.err.connection.ldap.user.notfound=U\u017eivatel {0} v LDAP nebyl nalezen
authentication.err.connection.ldap.manager.notfound=LDAP spr\u00e1vce {0} nebyl nalezen
authentication.err.connection.ldap.search=Nelze vyhled\u00e1vat v LDAP. D\u016fvod\: {0}

# PASSTHRU
authentication.err.connection.passthru.server=Nepoda\u0159ilo se otev\u0159\u00edt relaci s PASSTHRU serverem
authentication.err.passthru.token.unsupported=Nepodporovan\u00fd autentiza\u010dn\u00ed typ tokenu
authentication.err.passthru.guest.notenabled=P\u0159ihl\u00e1\u0161en\u00ed hosta je zak\u00e1z\u00e1no
authentication.err.passthru.user.disabled=\u00da\u010det je zak\u00e1z\u00e1n
authentication.err.passthru.user.notfound=PASSTHRU u\u017eivatel {0} nebyl nalezen

# Authentication Diagnostic Steps
authentication.step.ldap.validation=Ov\u011b\u0159ov\u00e1n\u00ed po\u017eadavku
authentication.step.ldap.connecting=P\u0159ipojuji se k LDAP serveru {0} 
authentication.step.ldap.connected=P\u0159ipojeno k LDAP serveru {0} s autoritou (principal)\: {1}
authentication.step.ldap.lookup=Vyhled\u00e1n\u00ed Testovac\u00edho u\u017eivatelsk\u00e9ho ID\: {0} s dotazem\: {1}
authentication.step.ldap.lookedup=Vyhled\u00e1no ID testovac\u00edho u\u017eivatele\: {0}, nalezeno rozli\u0161ovac\u00ed jm\u00e9no (DN)\: {1}
authentication.step.ldap.format.user=Specifikovan\u00fd form\u00e1t p\u0159ihla\u0161ovac\u00edho jm\u00e9na a identifikace u\u017eivatele (slo\u017een\u00fd z userNameFormat\: {2} a userId\: {0}) vytv\u00e1\u0159\u00ed DN\: {1}
authentication.step.ldap.authentication=Ov\u011b\u0159it u\u017eivatelsk\u00e9 ID\: {0}


# Sync Summary message 
synchronization.summary.status=Bylo zpracov\u00e1no {0} u\u017eivatel\u016f a {1} skupin


# Error messages
authentication.ldap.validation.authenticator.notfound=Autentik\u00e1tor nebyl nalezen

# Synchronization Diagnostic Steps
synchronization.step.users=Nalezeno {0} u\u017eivatel\u016f
synchronization.step.groups=Nalezeno {0} skupin
synchronization.step.users.lastsynced={0} \u00fasp\u011b\u0161n\u011b synchronizovan\u00fdch u\u017eivatel\u016f p\u0159i posledn\u00ed synchronizaci
synchronization.step.groups.lastsynced={0} \u00fasp\u011b\u0161n\u011b synchronizovan\u00fdch skupin p\u0159i posledn\u00ed synchronizaci

synchronization.err.ldap.search=P\u0159i hled\u00e1n\u00ed v LDAP do\u0161lo k chyb\u011b. D\u016fvod\: {0}
synchronization.err.ldap.get.user.id.missing=Chyb\u00ed userId (DN \= {0}, attributeName \= {1})
synchronization.err.ldap.get.group.id.missing=Chyb\u00ed groupId (DN \= {0}, attributeName \= {1})

synchronization.err.ldap.search.base.invalid=Chybn\u00e1 "search base" {0}. D\u016fvod\: {1}

synchronization.err.ldap.group.member.missing.exception=Nepoda\u0159ilo se identifikovat \u010dlena skupiny {0} s DN\: {1}, d\u016fvod {2};
synchronization.err.ldap.group.member.missing=Nepoda\u0159ilo se identifikovat \u010dlena skupiny {0} s DN\: {1};








