#X-Generator: crowdin.com
# authentication error messages
authentication.err.validation.authenticator.notfound=Nie mo\u017cna uwierzytelni\u0107, wystawca uwierzytelnienia o nazwie {0}, nie znaleziony
authentication.err.validation.authenticator.notactive=Wystawca uwierzytelnienia jest nieaktywny

authentication.err.authentication=Nie mo\u017cna uwierzytelni\u0107, nazwa u\u017cytkownika lub has\u0142o jest b\u0142\u0119dne. Nazwa u\u017cytkownika\: {0} Pow\u00f3d {1}
authentication.err.connection=Nie mo\u017cna po\u0142\u0105czy\u0107 si\u0119 z {0}. Pow\u00f3d {1}
authentication.err.communication=Nie mo\u017cna komunikowa\u0107 si\u0119 z {0}. Pow\u00f3d {1}

# LDAP error messages
authentication.err.connection.ldap.authenticator.unknownhost=Nie uda\u0142o si\u0119 po\u0142\u0105czy\u0107, ldap hosta {0} jest nieznany
authentication.err.connection.ldap.user.notfound=LDAP u\u017cytkownika {0} nie odnaleziony
authentication.err.connection.ldap.manager.notfound=U\u017cytkownik zarz\u0105dzaj\u0105cy LDAP {0} nie odnaleziony
authentication.err.connection.ldap.search=Wyszukanie LDAP nie jest mo\u017cliwe. Pow\u00f3d {0}

# PASSTHRU
authentication.err.connection.passthru.server=Nie mo\u017cna otworzy\u0107 sesji dla serwera passthru 
authentication.err.passthru.token.unsupported=Typ tokenu uwierzytelniania nieobs\u0142ugiwany
authentication.err.passthru.guest.notenabled=Logowania Go\u015bci wy\u0142\u0105czone
authentication.err.passthru.user.disabled=Konto wy\u0142\u0105czone
authentication.err.passthru.user.notfound=Nie mo\u017cna odnale\u017a\u0107 u\u017cytkownika PassThru  {0} 

# Authentication Diagnostic Steps
authentication.step.ldap.validation=Sprawdzanie poprawno\u015bci \u017c\u0105dania
authentication.step.ldap.connecting=Nawi\u0105zywanie po\u0142\u0105czenia z serwerem LDAP {0} 
authentication.step.ldap.connected=Po\u0142\u0105czono z serwerem LDAP {0} z g\u0142\u00f3wnym\: {1}
authentication.step.ldap.lookup=Identyfikator u\u017cytkownika testowego\: {0} z zapytania\: {1}
authentication.step.ldap.lookedup=Identyfikator u\u017cytkownika testowego\: {0} znaleziono wyr\u00f3\u017cnion\u0105 nazw\u0119 (DN)\: {1}
authentication.step.ldap.format.user=Format nazwy u\u017cytkownika okre\u015blony, userNameFormat\: {2} identyfikator {0} aby utworzy\u0107 nazw\u0119 wyr\u00f3\u017cnion\u0105 (DN)\: {1}
authentication.step.ldap.authentication=Uwierzytelnij identyfikator u\u017cytkownika\: {0}


# Sync Summary message 
synchronization.summary.status={0} u\u017cytkownik\u00f3w i {1} grup przetworzonych


# Error messages
authentication.ldap.validation.authenticator.notfound=Wystawca uwierzytelnienia nieodnaleziony

# Synchronization Diagnostic Steps
synchronization.step.users=Znaleziono {0} u\u017cytkownik\u00f3w
synchronization.step.groups=Znaleziono {0} grup
synchronization.step.users.lastsynced={0} ostatnio pomy\u015blnie zsynchronizowanych u\u017cytkownik\u00f3w
synchronization.step.groups.lastsynced={0} ostatnio pomy\u015blnie zsynchronizowanych grup

synchronization.err.ldap.search=Wyst\u0105pi\u0142 b\u0142\u0105d podczas wyszukiwania LDAP. Pow\u00f3d\: {0}
synchronization.err.ldap.get.user.id.missing=U\u017cytkownik nie posiada atrybutu identyfikatora DN \= {0}, attributeName \= {1})
synchronization.err.ldap.get.group.id.missing=Grupa nie posiada atrybutu identyfikatora DN \= {0}, attributeName \= {1})

synchronization.err.ldap.search.base.invalid=Nieprawid\u0142owa baza wyszukiwania {0} Pow\u00f3d\: {1}

synchronization.err.ldap.group.member.missing.exception="Nie uda\u0142o si\u0119 rozwi\u0105za\u0107 cz\u0142onka grupy {0} za pomoc\u0105 nazwy wyr\u00f3\u017cnionej\: {1}, pow\u00f3d {2});
synchronization.err.ldap.group.member.missing="Nie uda\u0142o si\u0119 rozwi\u0105za\u0107 cz\u0142onka grupy {0} za pomoc\u0105 nazwy wyr\u00f3\u017cnionej\: {1});








