#X-Generator: crowdin.com
# authentication error messages
authentication.err.validation.authenticator.notfound=Chyba overenia, overovate\u013e s menom, {0}, nebol n\u00e1jden\u00fd
authentication.err.validation.authenticator.notactive=Overovate\u013e nie je akt\u00edvny

authentication.err.authentication=Chyba overenia, meno alebo heslo nie s\u00fa spr\u00e1vne. Pou\u017e\u00edvate\u013e\:{0} D\u00f4vod {1}
authentication.err.connection=Chyba pripojenia k {0}. D\u00f4vod {1}
authentication.err.communication=Chyba komunik\u00e1cie s {0}. D\u00f4vod {1}

# LDAP error messages
authentication.err.connection.ldap.authenticator.unknownhost=Chyba pripojenia, LDAP server {0} je nezn\u00e1my
authentication.err.connection.ldap.user.notfound=Pou\u017e\u00edvate\u013e {0} nebol n\u00e1jden\u00fd v LDAP
authentication.err.connection.ldap.manager.notfound=Spr\u00e1vca {0} nebol n\u00e1jden\u00fd v LDAP
authentication.err.connection.ldap.search=Nie je mo\u017en\u00e9 vyh\u013ead\u00e1va\u0165 v LDAP, z d\u00f4vodu {0}

# PASSTHRU
authentication.err.connection.passthru.server=Nepodarilo sa otvori\u0165 rel\u00e1ciu na passthru server
authentication.err.passthru.token.unsupported=Nepodporovan\u00fd typ overovacieho tokenu
authentication.err.passthru.guest.notenabled=Zak\u00e1zan\u00e9 prihl\u00e1senie ako hos\u0165
authentication.err.passthru.user.disabled=Zak\u00e1zan\u00fd \u00fa\u010det
authentication.err.passthru.user.notfound=Passthru u\u017e\u00edvate\u013e {0} sa nena\u0161iel

# Authentication Diagnostic Steps
authentication.step.ldap.validation=Overenie \u017eiadosti
authentication.step.ldap.connecting=Pripojenie na LDAP Server {0}
authentication.step.ldap.connected=Pripojen\u00fd na LDAP server {0} s hlavn\u00fdm\: {1}
authentication.step.ldap.lookup=Vyh\u013ead\u00e1vanie userId\: {0} sk\u00fa\u0161obn\u00e9ho u\u017e\u00edvate\u013ea s dotazom\: {1}
authentication.step.ldap.lookedup=Vyh\u013eadan\u00e9 userId sk\u00fa\u0161obn\u00e9ho u\u017e\u00edvate\u013ea\: {0}, na\u0161iel sa rozli\u0161uj\u00faci n\u00e1zov (DN)\: {1}
authentication.step.ldap.format.user=Form\u00e1t u\u017e\u00edvate\u013esk\u00e9ho mena zadan\u00fd, userNameFormat\: {2} form\u00e1t ID u\u017e\u00edvate\u013ea userId\: {0} aby rozli\u0161uj\u00faci n\u00e1zov (DN)\: {1}
authentication.step.ldap.authentication=Overi\u0165 ID u\u017e\u00edvate\u013ea\: {0}


# Sync Summary message 
synchronization.summary.status={0} pou\u017e\u00edvate\u013e(ov) a {1} skupina(y) spracovan\u00e9


# Error messages
authentication.ldap.validation.authenticator.notfound=Overovate\u013e nen\u00e1jden\u00fd

# Synchronization Diagnostic Steps
synchronization.step.users=N\u00e1jden\u00fdch {0} pou\u017e\u00edvate\u013eov
synchronization.step.groups=N\u00e1jden\u00fdch {0} skup\u00edn
synchronization.step.users.lastsynced=Naposledy \u00faspe\u0161ne synchronizovan\u00ed u\u017e\u00edvatelia {0}
synchronization.step.groups.lastsynced=Naposledy \u00faspe\u0161ne synchronizovan\u00e9 skupiny {0}

synchronization.err.ldap.search=Chyba pri vyh\u013ead\u00e1van\u00ed LDAP. D\u00f4vod\: {0}
synchronization.err.ldap.get.user.id.missing=U\u017e\u00edvate\u013e s ch\u00fdbaj\u00facim u\u017e\u00edvate\u013esk\u00fdm id atrib\u00fat DN \= {0}, attributeName \= {1})
synchronization.err.ldap.get.group.id.missing=Skupina s ch\u00fdbaj\u00facim id atrib\u00fatom skupiny DN \= {0}, attributeName \= {1})

synchronization.err.ldap.search.base.invalid=Neplatn\u00e1 vyh\u013ead\u00e1vacia z\u00e1klad\u0148a {0} d\u00f4vod\: {1}

synchronization.err.ldap.group.member.missing.exception="Nepodarilo sa n\u00e1js\u0165 \u010dlena skupiny {0} s rozli\u0161uj\u00facim n\u00e1zvom\: {1}, d\u00f4vod {2});
synchronization.err.ldap.group.member.missing="Nepodarilo sa n\u00e1js\u0165 \u010dlena skupiny {0} s rozli\u0161uj\u00facim n\u00e1zvom\: {1});








