#X-Generator: crowdin.com
# Content-related messages

content.content_missing=Falta o contido do n\u00f3\:\nn\u00f3\: {0}\nlector\: {1}\nContacte co administrador do seu sistema.
content.runtime_exec.property_moved=A propiedade \u00aberrorCodes\u00bb baixou \u00e1 clase RuntimeExec

index.recovery.out_of_date=Os \u00edndices non est\u00e1n sincronizados coa base de datos.
index.tracking.starting=Iniciouse a recuperaci\u00f3n dos \u00edndices.
index.tracking.complete=Conclu\u00edu a recuperaci\u00f3n dos \u00edndices.
index.tracking.progress=\ A procesar as transacci\u00f3ns arredor de {0}.
index.recovery.starting=Iniciouse a recuperaci\u00f3n dos \u00edndices\: {0} transacci\u00f3ns.
index.recovery.complete=Conclu\u00edu a recuperaci\u00f3n dos \u00edndices.
index.recovery.progress=\ {0} % conclu\u00eddo.
index.recovery.terminated=Conclu\u00edu a recuperaci\u00f3n dos \u00edndices.

node.archive.msg.busy=Hai unha operaci\u00f3n de purga ou de restauraci\u00f3n en progreso

content.http_reader.err.no_connection=Foi impos\u00edbel conectarse co servidor remoto de Alfresco mediante HTTP\: {0}
content.http_reader.err.no_authentication=O lector de HTTP non puido autenticarse no servidor remoto\: {0}  \n
content.http_reader.err.check_cluster=Aseg\u00farese de que ''replicateUpdates'' e ''replicateUpdatesViaCopy'' est\u00e1n activados para a cach\u00e9 ''org.alfresco.cache.ticketsCache''. Comprobe que a configuraci\u00f3n do cl\u00faster xeral \u00e9 correcta e est\u00e1 a funcionar.
content.http_reader.err.unrecognized=Produciuse un erro desco\u00f1ecido ao tentar descargar contido do servidor remoto\:\nServidor\: {0}\nContido\: {1}\nResposta de HTTP\: {2}

metadata.extraction.err.type_conversion=Fallou a extracci\u00f3n dos metadatos porque non foi pos\u00edbel converter un dos valores extra\u00eddos ao tipo requirido\:\nExtractor\: {0}\nQNme da propiedade de destino\: {1}\nTipo requirido\: {2}\nValor extra\u00eddo\:  {3}

transform.err.format_or_password=Non foi pos\u00edbel converter o contido, posibelmente debido a un ficheiro formatado incorrectamente ou protexido mediante contrasinal.

content.routing.err.invalid_default_store=''defaultStoreName'', ''{0}'' non se refire a un almac\u00e9n en ''storesByName'' ({1}).
